name: Wiki

on:
  gollum

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
       with:
          repository: ${{ github.event.repository.full_name }}.wiki
          ref: ${{ github.event.pages[0].sha }}
          fetch-depth: 2
     - name: Slack
       run: |
          url=${HTML_URL}/_compare/$(git rev-parse HEAD^)...$(git rev-parse HEAD)
          curl -X POST ${WEBHOOK_URL} \
               -H 'Content-type: application/json' \
               -d "{ \
                    \"blocks\": [{ \
                      \"type\": \"section\", \
                      \"text\":{ \
                        \"type\": \"mrkdwn\", \
                        \"text\": \"Wiki ${ACTION}: ${TITLE}\" \
                      }, \
                      \"accessory\": { \
                        \"type\": \"button\", \
                        \"text\": { \
                          \"type\": \"plain_text\", \
                          \"text\": \"Go to Detail\", \
                          \"emoji\": true \
                        }, \
                        \"value\": \"click_me_123\", \
                        \"url\": \"${url}\", \
                        \"action_id\": \"button-action\" \
                      } \
                    }] \
                  }"
       env:
          ACTION: ${{ github.event.pages[0].action }}
          TITLE: ${{ github.event.pages[0].title }}
          HTML_URL: ${{ github.event.pages[0].html_url }}
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
